### ISSUE TITLE
Why change from send() to call.value ?

### ISSUE THREAD

**Issue by ethers** [randao/randao#11]
Why change cf75c2060ec3c9f3fc33953a0f6561dde40ed1a1 ?

Contracts can call the external functions like `refundBounty` and then can proceed to do whatever the contract wants to do.  Why does randao need to give gas to the fallback function of external contracts?

**Comment by u2** [comment]
Change to `call.value()()` it is possible for contracts to interact with this service.

**Comment by ethers** [comment]
Is there an example?  If I'm a contract, why can't I call `refundBounty` and then whatever function next?

Here's my contract function:
```
function doSomething() {
  randao.refundBounty();
  doSomethingElse();
}
```

**Comment by u2** [comment]
```
      uint256 bountypot = c.consumers[msg.sender].bountypot;
      c.consumers[msg.sender].bountypot = 0;
      if (!msg.sender.call.value(bountypot)()) {
          c.consumers[msg.sender].bountypot = bountypot;
      }
```
This can protect against recursive attack.

**Comment by ethers** [comment]
I think you're safe from reentrancy because you've followed some good practices, but `call.value(...)()` should not be used by default: it should only be used when it's really needed and I'm not sure why a contract needs its fallback function to run, instead of running it's own `doSomethingElse` as in example above.

**Comment by u2** [comment]
Ok, thank you. I will revert this commit, for the potential attacking.
