### ISSUE TITLE
n grow the reward will reduce

### ISSUE THREAD

**Issue by onesmash** [randao/randao#20]
each participant will get (rp - 1500n * gasPrice - Ccost) / n from one time participation. So when n grow the reward will reduce, when reward is less than 0, no one else will take part in. Maybe I can manufacture the random number by stop other people joining 'The first phase'

**Comment by u2** [comment]
Yes, in theory, someone could manipulate the process. But if the final random number is valuable enough, it would attract more people joining in and become a multi-party game.
