### ISSUE TITLE
test Randao? 

### ISSUE THREAD

**Issue by emanuelecesari** [randao/randao#21]
Hello I would like to test **randao algorithm**.
But I dont undestand very well how do it. what is  the easy way to do it?
Could you help me?
Maybe write something in the **README** will help also other people.

**Comment by chatch** [comment]
There is a truffle javascript test that runs through the main flow: https://github.com/randao/randao/blob/master/test/randao.js

It has only one participant but it does demonstrate the

**Comment by u2** [comment]
Here is the https://github.com/randao/randao/blob/master/handbook.md.
