### ISSUE TITLE
还是不明白怎么用,我在合约里面怎么实现,怎么做才能参与获取随机数的过程?始终找不到一个完善的教程

### ISSUE THREAD

**Issue by zxyaust** [randao/randao#23]
我是菜鸟,这里面的介绍还是太少了,根本弄不懂怎么用,有入门教程吗?这个看起来像是给高级开发者的

**Comment by 54853315** [comment]
今天是2018年11月13日，我安装了最新的truffle和solity，run这份合约，一堆编译问题……
好不容易解决了几个，一编译，更多的问题出来了。
感觉已经不适用了。

**Comment by jonnyhsy** [comment]
@zxyaust @54853315 

We're building decentralized oracle service for multiple blockchains, and we've built an internal random beacon service for smart contract developers to use, with similar principles as mentioned in Randao's whitepaper, algorand & dfinity section. It's in alpha version and live on rinkeby testnet yet for now.

Please check our docs and example usage: https://dosnetwork.github.io/docs/#/contents/blockchains/ethereum. Also welcome to join telegram https://t.me/dosnetwork_en to look for help :)

**Comment by 54853315** [comment]
@zxyaust 我找到了一个可以正常运行的随机数github 开源项目，我这边跑的起来。推荐你试一试。你搜下github ： vitalikDICE

@jonnyhsy Thanks.

**Comment by u2** [comment]
https://github.com/randao/randao/blob/master/handbook.zh_CN.md

这里有中文的介绍，具体如何使用工具发送交易不在介绍范围之内。
