### ISSUE TITLE
what if not one use the random create by this contract

### ISSUE THREAD

**Issue by Petelin** [randao/randao#24]
if the profit is not huge, people will not in this game. 

if all player know each other, they can make fake the result.

**Comment by jonnyhsy** [comment]
@Petelin That's a typical issue in commit-reveal scheme. So in randao's whitepaper the way algorand + dfinity is recommended to generate high throughput yet secure random numbers, and actually I think this is in randao's original roadmap (see https://randao.org Q1 2018)

You also have an alternative now: 
We're building decentralized oracle service for multiple blockchains, and we've built an internal random beacon service for smart contract developers to use, with similar principles as mentioned in Randao's whitepaper, algorand & dfinity section. It's in alpha version and living on rinkeby testnet only for now.

Please check our docs and example usage: https://dosnetwork.github.io/docs/#/contents/blockchains/ethereum. Also welcome to join telegram https://t.me/dosnetwork_en to look for help :)
