### ISSUE TITLE
Where is the _campaignID set

### ISSUE THREAD

**Issue by retrone** [randao/randao#6]
In the *Randao.sol* file, you have a *_campaignID* variable:

```
  function newCampaign(uint32 _bnum, uint96 _deposit, uint8 _commitDeadline, uint8 _commitBalkline) returns (uint32 _campaignID) {
    if(block.number >= _bnum){ throw; }
    if(_commitDeadline <= 0){ throw; }
    if(_commitBalkline <= 0){ throw; }
    if(_commitDeadline >= _commitBalkline){ throw; }

    Campaign c = campaigns[_campaignID];
```

How is the *_campaignID* set?

**Comment by u2** [comment]
I don't remember I saw this odd trick.It's looks strange,but it really work well.
Maybe it's not a good practice, and not easily readable. I will change later.

**Comment by u2** [comment]
I don't member how I got this odd trick.But it's really workable.
Maybe it is not a good practice.I will refactor it later.

https://github.com/randao/randao/commit/67c1f263769f023b624bd52668eef4278cee90a5
