### ISSUE TITLE
Has a security audit been done on this contract? Who would like to discuss how to improve the security?

### ISSUE THREAD

**Issue by retrone** [randao/randao#7]
In light of the DAO hacks, I noticed things like a potentially exceptionally large callback loop (in `function callback`), which may fail, as there is a maximum limit to how much can be spent in a block (see *Loops and the Block Gas Limit* in this Ethereum [blog post](https://blog.ethereum.org/2016/06/10/smart-contract-security/)). I also noticed that you do a callback to a function I have signed up, which might lead to a recursive callback.

Those are just two potential risks in 3 minutes of reading. Is there a group that we can discuss together other potential holes in this contract?

**Comment by retrone** [comment]
I'll keep writing issues, in case anyone finds this useful:

- There's no check that a future secret/commitment has not been used in a previous campaign, which means we could continuously submit the same results, or at least predict what parts of the random will be
- As partially noted earlier, you do callbacks; if one callback fails, it will hold up everyone else's callback ( so consumers shouldn't depend on a callback)
- I can't see any code where you penalize participants who didn't reveal

Other notes
- As noted earlier, I can't see where you generate a _campaignId (assume that you should be in `function newCampaign`)
- Is it a fair assumption that calling `getRandom` should often lead to registering a function as a callback? It seems better to have a getter for the random (if set)? If that fails, another function lets you register

Anyway, this looks like you were just hacking - not attempting to create the perfect Randao or desiring to keep working on this, so I'll stop commenting further.

**Comment by u2** [comment]
Sorry about too late replying, I have not noticed this issue before.I forgot to watch the project. 😢 
Firstly, thanks for you suggestion.We have noticed the potentially security problem, but I am a little busy these days. I plan to improve the security later.
I really appreciated of your discussion.I will respond to you later, ok? And, welcome more valuable suggestion and PR.

**Comment by u2** [comment]
> There's no check that a future secret/commitment has not been used in a previous campaign, which means we could continuously submit the same results, or at least predict what parts of the random will be.

I think if anyone want to use the same commitment is ok, this is also a randomize situation.

> As partially noted earlier, you do callbacks; if one callback fails, it will hold up everyone else's callback ( so consumers shouldn't depend on a callback)

Yes, before youcai write a very complicated callback mechanism, but at last we found there were some problems about this method.I planed to refactor it, but not finished it yet.So the code looks in a mass.

> I can't see any code where you penalize participants who didn't reveal.

Before we have ,but during the refactor, I remove some code.

---

And now all the problems you mentioned have been fixed.Here is a new RANDAO.
