### ISSUE TITLE
One more security layer for RANDAO contract

### ISSUE THREAD

**Issue by tad88dev** [randao/randao#8]
I have been created a smart contract which was generate a uncontrollable number:
https://github.com/tad88dev/thedivine

Would you use it as a security improvement at the reveal round ?

**Comment by u2** [comment]
It's a interesting project.But I have not find the relationship with the reveal round?

**Comment by tad88dev** [comment]
In reveal round you call TheDivine.GetPower() to get a number, and combine to RANDAO result after funding all participants.

It will keep miner, attacker is not able to manipulate.

**Comment by tad88dev** [comment]
```
  function calculate(Campaign storage _c) private {
    for (uint i = 0; i < _c.paddresses.length; i++) {
      _c.random ^= _c.participants[_c.paddresses[i]].secret;
    }
  }
```
This lines if all participants sen 0x000000000000000000000.... to your contract your result isn't RANDOMIZE at all.
The weakness is you need 1 HONEST PARTICIPANT. And **The Divine** will be come "1 honest participant".

**Comment by u2** [comment]
Firstly, I will refactoring this piece of code, there is some security problem.
```
  function calculate(Campaign storage _c) private {
    for (uint i = 0; i < _c.paddresses.length; i++) {
      _c.random ^= _c.participants[_c.paddresses[i]].secret;
    }
  }
```
And then, why we don't add something like block[N].hash or block[N].difficulty? In our README, we have explained it.
> Q: Why not let the miners participate in RNG? Why not use tx hash, nonce and other blockchain data? A: Miners have the ability to manipulate these blockchain data, and thus can indirectly affect RNG. If RNG contains blockchain data, it will give the miners capacity to construct random numbers in their favor.

**Comment by u2** [comment]
Vitalik has thrown out his randao++ idea, it looks more reasonable.But firstly, we need to finish this.

**Comment by tad88dev** [comment]
I'm agree that we shouldn't trust the miner. And The Divine was created to protect us from miner manipulate.

**Comment by tad88dev** [comment]
```
        WorldTree = uint256(sha3(WorldTree,
            block.timestamp,
            msg.sender,
            block.difficulty));
```
The Divine is more legit when the number of user is lager.

**Comment by u2** [comment]
In the reveal round, only the revealer know the secret, and this is  the only one factor can effect the result. 
But in your design, the miner has the ability to effect the result.
After you reveal your secret, your secret, your address,WorldTree and the block.difficulty is clear, and now the timestamp is the determinant, this means that the miner is the last one who has the ability to effect the result!
And I don't think more elements including, means more RANDOMIZE.

**Comment by u2** [comment]
Yes, the weakness is that we need at least 1 HONEST PARTICIPANT, but I take this as the precondition. 

> if all participants send 0x000000000000000000000.... to your contract your result isn't RANDOMIZE at all.
No, this is also randomize.

**Comment by tad88dev** [comment]
All participants are send malicious secrets, your result is able to calculate and it no more a random number.

**Comment by u2** [comment]
We just need one honest participant.

**Comment by tad88dev** [comment]
> In the reveal round, only the revealer know the secret, and this is the only one factor which can effect the result. 

If miner was mine this block he will know secret too.

> But in your design, the miner has the ability to effect the result.
> After you reveal your secret, your secret, your address,WorldTree and the block.difficulty is clear, and now the timestamp is the determinant, this means that the miner is the last one who has the ability to effect the result!
> And I don't think more elements including, means more RANDOMIZE.

I've suppose to remove block.timestamp that is my stupid.

> We just need one honest participant.
RNG should trusted anyone or anything instead of participant.

**Comment by u2** [comment]
Yes, the RANDAO has two weakness:
1. At least one honest participant
2. The last one revealer cheating.

But it is the reasonable design we can think by now.

**Comment by tad88dev** [comment]
I have remove `block.timestamp` and explain why was `block.difficulty`.

I hope that **The Divine** may be an improvement for RANDAO, let's us work together.

**Comment by tad88dev** [comment]
Here is the concept to make **The Divine** and **Randao** working together.
* Each time participants do a commitment: **Randao** call to **The Divine** and store number to A[]
* In reveal round:
    * Let X = sha3(X1,X2,....Xn)
    * Let K = A[X % A.length] //Make sure that miner don't know which to manipulate.
    * Result = sha3(randao.Random, K)

**Comment by u2** [comment]
Sorry, I do not get the meaning of `X1, X2, Xn` ?

**Comment by tad88dev** [comment]
> Sorry, I do not get the meaning of X1, X2, Xn ?

It's participant secrets. Sorry, i wasn't make it clear.

Here is my latest concept:
https://docs.google.com/document/d/1quNacg6A-Cm9QFUJx5HzMmrqjIULRbt2hsF6sx6Hm8E/edit

**Comment by u2** [comment]
> Round 1: Collect hash of hash of secrets from participants
Collect from participants: SHA-32(Yi)

>  Round 2: Reveal secret
Let k = SHA-3(Yi)
Let q = k % m
Result = SHA-3(Yi, A[q])

Firstly, why we need `sha3^2`? 
And what's the meaning for the `m`?

**Comment by tad88dev** [comment]
This is concept about save all random value in the part and lookup later.
sha3^2(x) mean sha3(sha3(x)) 
sha3^n(x)  sha3 n times of x
m is total number of random number have store in the past.
----------------------------------------------------------------------------
I have make a pull request which is based on “anyone can make change”.
